### Variables
@base = http://localhost:3000

### Health Check
GET {{base}}
Accept: application/json

### Get All Users
GET {{base}}/users
Accept: application/json

### Create User
POST {{base}}/users
Content-Type: application/json

{
  "name": "Shovu",
  "email": "shvou@gmail.com"
}

### Get User by ID
GET {{base}}/users/2
Accept: application/json

### Update User
PUT {{base}}/users/2
Content-Type: application/json

{
  "name": "Shovu",
  "email": "shovu1@email.com"
}

### Delete User
DELETE {{base}}/users/1
Accept: application/json


### Get all Posts
GET {{base}}/posts
Accept: application/json

### Get Post by ID
GET {{base}}/posts/1
Accept: application/json

### Create Post
POST {{base}}/posts
Content-Type: application/json

{
  "title": "Post 1",
  "content": "Content 1",
  "published": true,
  "authorId": 1
}

### Update Post
PUT {{base}}/posts/1
Content-Type: application/json

{
  "title": "Post 1 Updated",
  "content": "Content 1 Updated",
  "authorId": 1
}

### Delete Post
DELETE {{base}}/posts/1
Accept: application/json

### Get all Comments
GET {{base}}/comments
Accept: application/json

### Get Comment
GET {{base}}/comments/1
Accept: application/json

### Create Comment
POST {{base}}/comments
Content-Type: application/json

{
  "content" : "comment 3",
  "postId" : 1,
  "authorId" : 2
}

### Update Comment
PUT {{base}}/comments/1 HTTP/1.1
Content-Type: application/json

{
  "content" : "comment 3 updated",
  "postId" : 1,
  "authorId" : 2
}

### Delete Comment
DELETE {{base}}/comments/1 HTTP/1.1
Accept: application/json

### Get all Likes
GET {{base}}/likes
Accept: application/json

### Get Like
GET {{base}}/likes/2
Accept: application/json

### Toggle Like
POST {{base}}/likes
Content-Type: application/json

{
  "postId": 1,
  "userId": 1
}

